Repository simphony/simphony-osp, pull requests merged in 2021-07, with the labels that each got.

#666 Raise a warning instead of an error when the default relationship of …
  osp/core/ontology/ontology.py
Labels: bug :bug:

#663 Fetch datatypes from Sparql-Result
  osp/core/session/sparql_backend.py
  tests/test_sparql.py
Labels: API details, simple fix :hammer:

#668 662 Strange behaviour of CUDS remove (DataspaceSession)
  osp/core/cuds.py
  osp/core/utils/wrapper_development.py
  tests/test_api_city.py
Labels: bug :bug:

#667 652 cuba.file in dataspace session shows wrong file path on second load
  osp/core/session/transport/transport_utils.py
  tests/test_filetransfer.py
Labels: bug :bug:

#672 xsd:double support, enforce rdflib >= 5.0.0.
  osp/core/ontology/datatypes.py
  setup.py
Labels: simple fix :hammer:

#673 Bump version to 3.5.4
  packageinfo.py
Labels: simple fix :hammer:

#681 Hotfix PRs #676, #678
  packageinfo.py
  setup.py
Labels: critical :warning:
