Repository simphony/simphony-osp, pull requests merged in 2022-12, with the labels that each got.

#834 Use runners labeled with `simphony-osp` for the CI (`release/4/dev`)
  .github/workflows/ci.yml
Labels: :syringe: testing

#835 Use runners labeled with `simphony-osp` for the CI (`dev`)
  .github/workflows/ci.yml
Labels: :syringe: testing

#833 Use BFS in `find` function and variants
  simphony_osp/tools/search.py
Labels: :bug: bug

#836 Remove dockerfile
  Dockerfile
Labels: :construction: installation, :zap: breaking change

#830 Enh/schema validation attribute values
  osp/core/utils/schema_validation.py
  tests/test_utils.py
  tests/test_validation_schema_city_with_attribute_value.yml
Labels: data model, :seedling: new feature, :scroll: ontology
